<?
/**
	* userstruct.inc
	*
	* Describes what a user is.  In the format of ["Type"]["Name"] = "sqlval"
	* In doing this, to generate user information we need to parse
	* over the variable in the format of foreach ($userstruct as $key=>$val)
	*
	* @author		David Walker (azrail@csh.rit.edu)
	*/

$positions[] = "Emminent Archon";
$positions[] = "Emminent Depudy Archon";
$positions[] = "Emminent Doo-Dad";
