<?
/**
 * calendar_view.php
 *
 * View the Calendar
 *
 * @author		David Walker (azrail@csh.rit.edu)
 */

include_once ('./basePath.inc');
include_once (PORTALROOT.'shared/portalBase.inc');
require_once ('web_func.inc');
global $portal;
?>

<box>

<iframe src="http://www.google.com/calendar/embed?src=saenytg%40gmail.com&amp;chrome=NAVIGATION&amp;height=600&amp;wkst=1" style=" border-width:0 " width="800" frameborder="0" height="610" scrolling="no"></iframe>

</box>
